import { FieldItemPatchInterface } from '../../../../pop-common.model';
import { SetControl } from '../../../../pop-common-dom.models';
import { NumberConfig } from '../pop-number/number-config.model';
import { SwitchConfig } from '../pop-switch/switch-config.model';
export interface MinMaxConfigInterface {
    allowNegative?: boolean;
    bubble?: boolean;
    disabled?: boolean;
    displayErrors?: boolean;
    helpText?: string;
    id?: string | number;
    facade?: boolean;
    label?: string;
    limit?: number;
    minValue?: number;
    maxValue?: number;
    minReadonly?: boolean;
    maxReadonly?: boolean;
    min?: number;
    max?: number;
    minRequired?: boolean;
    maxRequired?: boolean;
    minColumn?: string;
    maxColumn?: string;
    minimal?: boolean;
    minLabel?: string;
    maxLabel?: string;
    metadata?: object;
    patch?: FieldItemPatchInterface;
    session?: boolean;
    sessionPath?: string;
    tooltip?: string;
}
export declare class MinMaxConfig implements SetControl {
    allowNegative?: boolean;
    bubble: boolean;
    control: any;
    disabled: boolean;
    facade: boolean;
    helpText: string;
    id: string;
    isMinConfig: SwitchConfig;
    isMaxConfig: SwitchConfig;
    label: string;
    limit: number;
    minValue: number;
    maxValue: number;
    min: number;
    max: number;
    minColumn: string;
    maxColumn: string;
    minReadonly: boolean;
    maxReadonly: boolean;
    minConfig: NumberConfig;
    minRequired?: boolean;
    maxConfig: NumberConfig;
    maxRequired?: boolean;
    minDefaultValue?: number;
    maxDefaultValue?: number;
    minLabel: string;
    maxLabel: string;
    minimal: false;
    metadata: any;
    message: string;
    name: any;
    pattern: any;
    patch: FieldItemPatchInterface;
    session?: boolean;
    sessionPath?: string;
    showTooltip: boolean;
    tooltip: string;
    triggerOnChange: any;
    transformation: any;
    validators: any;
    value: string;
    constructor(params?: MinMaxConfigInterface);
    setControl(): void;
}
