import { FormControl, ValidatorFn } from '@angular/forms';
import { FieldItemOptions, FieldItemPatchInterface } from '../../../../pop-common.model';
import { SetControl } from '../../../../pop-common-dom.models';
export interface SelectFilterGroupInterface {
    label: string;
    options: FieldItemOptions;
    all?: boolean;
    indeterminate?: boolean;
    groupFk: number;
    visible?: number;
    open?: boolean;
    selected?: number;
}
export interface SelectFilterConfigInterface {
    allLabel?: string;
    all?: boolean;
    allValue?: boolean | string | number | null | any[];
    allowAll?: boolean;
    bubble?: boolean;
    checkboxPosition?: string;
    collapsed?: boolean;
    control?: FormControl;
    disabled?: boolean;
    displayErrors?: boolean;
    emptyLabel?: string;
    emptyValue?: boolean | string | number | null | any[];
    float?: boolean;
    filter?: boolean;
    facade?: boolean;
    helpText?: string;
    height?: number;
    id?: number | string;
    levelGap?: number;
    label?: string;
    metadata?: object;
    multiple?: boolean;
    name?: string;
    noInitialValue?: boolean;
    options?: FieldItemOptions;
    patch?: FieldItemPatchInterface;
    patchGroupFk?: boolean;
    session?: boolean;
    sessionPath?: string;
    sort?: boolean;
    position?: 'above' | 'below';
    value?: Array<number | string> | number | string;
    validators?: Array<ValidatorFn>;
}
export declare class SelectFilterConfig implements SetControl {
    allLabel: string;
    all: boolean;
    allValue: any;
    allowAll: boolean;
    bubble: boolean;
    displayErrors: boolean;
    collapsed: boolean;
    checkboxPosition: string;
    control: FormControl;
    defaultHeight: any;
    defaultMinHeight: number;
    disabled: boolean;
    emptyValue: any;
    emptyLabel: any;
    facade: boolean;
    float?: boolean;
    filter: boolean;
    groups: SelectFilterGroupInterface[];
    helpText: string;
    height: number;
    id: number | string;
    label: string;
    levelGap: number;
    message: string;
    metadata: any;
    minHeight: number;
    multiple: boolean;
    name: string;
    noInitialValue: boolean;
    offset: any;
    offsetSession: any;
    options?: FieldItemOptions;
    patch: FieldItemPatchInterface;
    patchGroupFk: boolean;
    position: any;
    session?: boolean;
    sessionPath?: string;
    sort: boolean;
    selectedOptions: any[];
    strVal: string;
    value?: Array<number | string> | number | string;
    validators: Array<ValidatorFn>;
    route: any;
    constructor(params?: SelectFilterConfigInterface);
    setControl(): void;
    private setDefaultValues;
    private getOptionGroups;
    resetSelection(): void;
    addSelectedOption(option: number): void;
}
