import { FormControl, Validators } from '@angular/forms';
import { FieldItemPatchInterface } from '../../../../pop-common.model';
import { SetControl } from '../../../../pop-common-dom.models';
export interface ButtonConfigInterface {
    bubble?: boolean;
    color?: 'accent' | 'primary' | 'default';
    conceal?: boolean;
    control?: FormControl;
    disabled?: boolean;
    displayErrors?: boolean;
    event?: string;
    helpText?: string;
    hidden?: boolean;
    icon?: string;
    iconColor?: 'accent' | 'primary' | 'default';
    id?: string | number;
    label?: string;
    metadata?: object;
    name?: string;
    patch?: FieldItemPatchInterface;
    radius?: number;
    size?: number;
    text?: number;
    tooltip?: string;
    type?: 'mat-button' | 'mat-raised-button' | 'mat-flat-button';
    validators?: Array<Validators>;
    value?: string | number;
    width?: number;
}
export declare class ButtonConfig implements SetControl {
    control: any;
    color: 'accent' | 'primary' | 'default';
    bubble: boolean;
    displayErrors: boolean;
    disabled: boolean;
    event?: string;
    helpText: string;
    hidden: boolean;
    icon: string;
    iconColor: 'accent' | 'primary' | 'default';
    id: string;
    label: string;
    message: string;
    metadata: any;
    name: string;
    patch: any;
    radius: number;
    size: number;
    showTooltip: boolean;
    text: number;
    tooltip: string;
    type: string;
    transformation: any;
    validators: any;
    triggerOnChange: any;
    value: string;
    width: any;
    constructor(params?: ButtonConfigInterface);
    setControl(): void;
}
