import { FormControl, Validators } from '@angular/forms';
import { FieldItemOption, FieldItemOptions, FieldItemPatchInterface } from '../../../../pop-common.model';
import { SetControl } from '../../../../pop-common-dom.models';
export interface SelectConfigInterface {
    autoFill?: boolean;
    bubble?: boolean;
    control?: FormControl;
    disabled?: boolean;
    displayErrors?: boolean;
    emptyOption?: FieldItemOption;
    empty?: 'ConvertEmptyToNull' | 'ConvertEmptyToZero';
    facade?: boolean;
    helpText?: string;
    height?: number;
    hidden?: boolean;
    id?: number | string;
    label?: string;
    metadata?: object;
    mode?: 'select' | 'label';
    minimal?: boolean;
    name?: string;
    noInitialValue?: boolean;
    options?: FieldItemOptions;
    patch?: FieldItemPatchInterface;
    route?: string;
    readonly?: boolean;
    required?: boolean;
    session?: boolean;
    sessionPath?: string;
    sort?: boolean;
    tooltip?: string;
    validators?: Array<Validators>;
    value?: boolean | string | number;
}
export declare class SelectConfig implements SetControl {
    autoFill?: boolean;
    bubble: boolean;
    clearMessage: any;
    control: FormControl;
    disabled: boolean;
    displayErrors: boolean;
    empty: any;
    facade: boolean;
    helpText: string;
    hidden: false;
    height?: number;
    id: any;
    label: string;
    message: string;
    mode: string;
    metadata: any;
    minimal: boolean;
    name: string;
    noInitialValue: boolean;
    options?: FieldItemOptions;
    patch: FieldItemPatchInterface;
    route: any;
    readonly: boolean;
    required?: boolean;
    showTooltip: boolean;
    sort: boolean;
    session?: boolean;
    sessionPath?: string;
    triggerOnChange: any;
    tooltip: string;
    validators: any;
    value?: boolean | string | number | any[];
    constructor(params?: SelectConfigInterface);
    setControl(): void;
}
