import { FormControl, Validators } from '@angular/forms';
import { FieldItemPatchInterface } from '../../../../pop-common.model';
import { SetControl } from '../../../../pop-common-dom.models';
export interface NumberConfigInterface {
    bubble?: boolean;
    column?: string;
    control?: FormControl;
    readonly?: boolean;
    disabled?: boolean;
    displayErrors?: boolean;
    dropSpecial?: boolean;
    facade?: boolean;
    helpText?: string;
    hidden?: boolean;
    id?: string | number;
    label?: string;
    metadata?: object;
    minimal?: boolean;
    min?: number;
    max?: number;
    noInitialValue?: boolean;
    name?: string;
    patch?: FieldItemPatchInterface;
    prefix?: string;
    session?: boolean;
    sessionPath?: string;
    suffix?: string;
    step?: number;
    showMask?: boolean;
    tooltip?: string;
    transformation?: any;
    validators?: Array<Validators>;
    value?: boolean | string | number;
}
export declare class NumberConfig implements SetControl {
    bubble: boolean;
    control: any;
    dropSpecial: boolean;
    displayErrors: boolean;
    disabled: boolean;
    facade?: boolean;
    helpText: string;
    hidden: boolean;
    id: string;
    label: string;
    message: string;
    min?: number;
    max?: number;
    metadata: any;
    minimal: boolean;
    maxlength: any;
    mask: string;
    name: string;
    noInitialValue: boolean;
    pattern: string;
    patch: FieldItemPatchInterface;
    prefix: string;
    readonly: boolean;
    session?: boolean;
    sessionPath?: string;
    showTooltip: boolean;
    specialChars: string[];
    showMask: boolean;
    suffix: string;
    step?: number;
    tooltip: string;
    transformation: any;
    triggerOnChange: any;
    triggerDirectPatch: any;
    value?: boolean | string | number;
    validators: any;
    constructor(params?: NumberConfigInterface);
    setControl(): void;
}
