import { FormControl, Validators } from '@angular/forms';
import { FieldItemOption, FieldItemPatchInterface } from '../../../../pop-common.model';
import { SetControl } from '../../../../pop-common-dom.models';
export interface SliderConfigInterface {
    autoTicks?: false;
    bubble?: boolean;
    column?: string;
    control?: FormControl;
    disabled?: boolean;
    displayErrors?: boolean;
    facade: boolean;
    helpText?: string;
    id?: number | string;
    label?: string;
    max?: number;
    min?: number;
    metadata?: object;
    noInitialValue?: boolean;
    patch?: FieldItemPatchInterface;
    session?: boolean;
    sessionPath?: string;
    showTicks?: true;
    step?: number;
    thumbLabel?: true;
    tickInterval?: number;
    validators?: Array<Validators>;
    value?: boolean | number | string;
}
export declare class SliderConfig implements SetControl {
    autoTicks: boolean;
    bubble: boolean;
    column: string;
    control: FormControl;
    displayErrors: boolean;
    disabled: boolean;
    facade: boolean;
    helpText: string;
    id: any;
    label: string;
    message: string;
    max: number;
    min: number;
    metadata: any;
    noInitialValue: boolean;
    options: FieldItemOption[];
    patch: FieldItemPatchInterface;
    session?: boolean;
    sessionPath?: string;
    step: number;
    showTooltip: boolean;
    showTicks: boolean;
    thumbLabel: boolean;
    tickInterval: number;
    tooltip: string;
    validators: any;
    value: boolean | number | string;
    constructor(params?: SliderConfigInterface);
    setControl(): void;
}
